In [11]:
import pandas as pd
data ={
    "name": ["Anton", "Ben", "Carl"],
    "age": [38,43,50],
    "city": ["Stockholm", "Göteborg", "Malmö"]
}

df = pd.DataFrame(data)
df.to_csv("people.csv", index=False)

df2=pd.read_csv("people.csv")
print(df2)
df2

    name  age       city
0  Anton   38  Stockholm
1    Ben   43   Göteborg
2   Carl   50      Malmö


name  age       city
0  Anton   38  Stockholm
1    Ben   43   Göteborg
2   Carl   50      Malmö

In [10]:
person = {"name": "Alex", "age": 26, "city": "Stockholm"}
print(person["name"])
print(person["age"])
person["language"] = "Swedish"
print(person["language"])



Alex
26
Swedish


In [15]:
favs = ["pizza", "ribs", "lasagne", "stew", "pie"]
print(favs[2])

movies={
    "title" : "Forrest Gump",
    "year" : 1994,
    "rating": 4.7
}

print(movies["rating"])


def iseven(a):
    return a%2==0

print(iseven(7))
print(iseven(4))

lasagne
4.7
False
True


In [19]:
data = {
    "date":["2025-10-25", "2025-10-26", "2025-10-27"],
    "temperature":[12.3, 11.2, 8.5]
}

df = pd.DataFrame(data)
df.to_csv("temps.csv", index=False)

df2 = pd.read_csv("temps.csv")
df2

date  temperature
0  2025-10-25         12.3
1  2025-10-26         11.2
2  2025-10-27          8.5

In [1]:
import numpy as np

arr = np.array([1,2,3,4,5])
print(arr)

print("Type:", type(arr))
print("Shape:", arr.shape)
print("Data Type:", arr.dtype)
print("Number of Elements:", arr.size)
print("ndim", arr.ndim)

[1 2 3 4 5]
Type: <class 'numpy.ndarray'>
Shape: (5,)
Data Type: int64
Number of Elements: 5
ndim 1


In [3]:
z = np.zeros(5)
o = np.ones((3,2))
print("z", z)
print("o (3x2):\n",o)

z [0. 0. 0. 0. 0.]
o (3x2):
 [[1. 1.]
 [1. 1.]
 [1. 1.]]


In [5]:
hourly = np.arange(24*3).reshape(24,3)
offset = np.array([0,100,200])
adjusted = hourly + offset
print("hourly[0:3]:\n", hourly[0:3])
print("adjusted[0:3]:\n",adjusted[0:3])

hourly[0:3]:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
adjusted[0:3]:
 [[  0 101 202]
 [  3 104 205]
 [  6 107 208]]


In [7]:
import numpy as np

a = np.arange(12)   # 12 numbers → [0, 1, 2, ..., 11]
b = a.reshape(3, 4) # reshape to 3 rows × 4 columns

print("a shape:", a.shape)
print(a)
print("b shape:", b.shape)
print(b)

a shape: (12,)
[ 0  1  2  3  4  5  6  7  8  9 10 11]
b shape: (3, 4)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [19]:
a = np.linspace(0, 10, 5)
a


array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [45]:
import numpy as np

np.random.seed(42)
temperatures = np.round(np.random.normal(loc=10, scale=3, size=30),1)

temperatures[5] = np.nan
temperatures[12] = 99.9

print("Temperature Data:", temperatures)

print(temperatures.shape)
print(temperatures.dtype)
print(np.nanmin(temperatures))
print(np.nanmax(temperatures))
print(np.round(np.nanmean(temperatures),1))
print(temperatures.size)

invalid = (temperatures > 40) | (temperatures < -30)
print (invalid)
cleaned = np.where(invalid, np.nan, temperatures)
print (cleaned)

print(np.nanmin(cleaned))
print(np.nanmax(cleaned))
print(np.round(np.nanmean(cleaned),1))

Temperature Data: [11.5  9.6 11.9 14.6  9.3  nan 14.7 12.3  8.6 11.6  8.6  8.6 99.9  4.3
  4.8  8.3  7.  10.9  7.3  5.8 14.4  9.3 10.2  5.7  8.4 10.3  6.5 11.1
  8.2  9.1]
(30,)
float64
4.3
99.9
12.5
30
[False False False False False False False False False False False False
  True False False False False False False False False False False False
 False False False False False False]
[11.5  9.6 11.9 14.6  9.3  nan 14.7 12.3  8.6 11.6  8.6  8.6  nan  4.3
  4.8  8.3  7.  10.9  7.3  5.8 14.4  9.3 10.2  5.7  8.4 10.3  6.5 11.1
  8.2  9.1]
4.3
14.7
9.4
